<x-portal-shell title="Patient Dashboard">
<div class="mb-7 flex flex-col justify-between gap-4 md:flex-row md:items-end">
 <div><span class="section-label">PATIENT PORTAL</span><h1 class="section-heading !mt-3 !text-4xl">Welcome back, {{ auth()->user()->name }}</h1><p class="mt-3 text-slate-500">Your appointments, reports and patient-visible medical information in one secure place.</p></div>
 <a href="{{route('appointments.create')}}" class="btn-primary">Book Appointment <span>↗</span></a>
</div>
<div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
 @foreach([['Upcoming appointment',$nextAppointment?->appointment_date?->format('d M Y') ?? 'None'],['Total appointments',$totalAppointments],['Medical reports',$reportCount],['Unread notifications',$unreadCount]] as $s)<div class="stat-card"><p class="text-sm font-bold text-slate-500">{{$s[0]}}</p><p class="mt-2 text-2xl font-extrabold text-navy-900">{{$s[1]}}</p></div>@endforeach
</div>
<div class="mt-6 grid gap-6 xl:grid-cols-[1.25fr_.75fr]">
 <section class="soft-panel p-6"><div class="flex items-center justify-between"><div><span class="section-label">NEXT VISIT</span><h2 class="mt-3 text-xl font-extrabold text-navy-900">Upcoming appointment</h2></div></div>
 @if($nextAppointment)<div class="mt-5 rounded-3xl bg-[linear-gradient(135deg,#071c40,#164f9c)] p-6 text-white"><p class="text-sm font-bold text-white/60">{{$nextAppointment->appointment_date->format('l, d M Y')}} · {{substr($nextAppointment->appointment_time,0,5)}}</p><p class="mt-2 text-2xl font-extrabold">{{$nextAppointment->doctor->name}}</p><p class="mt-1 text-white/70">{{$nextAppointment->doctor->specialty?->name}}</p><span class="mt-5 inline-flex rounded-full bg-white/10 px-3 py-1 text-xs font-bold">{{ucfirst($nextAppointment->status)}}</span></div>@else<div class="mt-5 rounded-3xl bg-slate-50 p-8 text-center"><p class="font-bold text-navy-900">No upcoming appointment</p><p class="mt-1 text-sm text-slate-500">Book your next visit when you're ready.</p></div>@endif
 </section>
 <section class="soft-panel p-6"><div class="flex items-center justify-between"><h2 class="text-xl font-extrabold text-navy-900">Notifications</h2><a href="{{route('patient.notifications')}}" class="text-sm font-bold text-primary-700">View all</a></div><div class="mt-4 divide-y divide-slate-100">@forelse($notifications as $n)<div class="block py-4"><p class="font-bold text-navy-900">{{$n->title}}</p><p class="mt-1 text-sm text-slate-500">{{$n->message}}</p>@if(!$n->read_at)<form method="POST" action="{{route('patient.notifications.read',$n)}}" class="mt-2">@csrf<button class="text-xs font-extrabold text-primary-700">View update →</button></form>@endif</div>@empty<p class="py-8 text-sm text-slate-500">You're all caught up.</p>@endforelse</div></section>
</div>
<section class="soft-panel mt-6 p-6"><div class="flex items-center justify-between"><div><span class="section-label">SECURE DOCUMENTS</span><h2 class="mt-3 text-xl font-extrabold text-navy-900">Medical Reports</h2></div><a href="{{route('patient.reports')}}" class="text-sm font-bold text-primary-700">View all</a></div><div class="mt-5 grid gap-4 md:grid-cols-2">@forelse($reports as $r)<div class="rounded-3xl border border-slate-100 bg-slate-50 p-5"><div class="flex items-start justify-between gap-4"><div><p class="font-extrabold text-navy-900">{{$r->title}}</p><p class="mt-1 text-sm text-slate-500">{{$r->doctor->name}} · {{$r->report_date->format('d M Y')}}</p></div><span class="rounded-full bg-white px-3 py-1 text-xs font-bold text-slate-500">{{strtoupper(pathinfo($r->file_name,PATHINFO_EXTENSION))}}</span></div><a href="{{route('medical-reports.download',$r)}}" class="mt-5 inline-flex font-extrabold text-primary-700">View / Download →</a></div>@empty<div class="rounded-3xl bg-slate-50 p-8 text-center text-sm text-slate-500 md:col-span-2">No medical reports yet.</div>@endforelse</div></section>
<section class="soft-panel mt-6 p-6"><span class="section-label">PATIENT-VISIBLE NOTES</span><h2 class="mt-3 text-xl font-extrabold text-navy-900">Recent clinical information</h2><div class="mt-5 grid gap-4 md:grid-cols-2">@forelse($medicalRecords as $r)<article class="rounded-3xl bg-slate-50 p-5"><p class="text-xs font-extrabold uppercase tracking-wider text-primary-600">{{optional($r->created_at)->format('d M Y')}}</p><p class="mt-2 text-sm leading-6 text-slate-600">{{$r->patient_visible_notes}}</p><p class="mt-3 text-xs font-bold text-slate-400">Dr. {{$r->doctor->name}}</p></article>@empty<div class="rounded-3xl bg-slate-50 p-8 text-center text-sm text-slate-500 md:col-span-2">No patient-visible clinical notes yet.</div>@endforelse</div></section>
</x-portal-shell>
