<?php if (isset($component)) { $__componentOriginalc0848eaf28452caa8d672e14d7fde2bc = $component; } ?>
<?php if (isset($attributes)) { $__attributesOriginalc0848eaf28452caa8d672e14d7fde2bc = $attributes; } ?>
<?php $component = Illuminate\View\AnonymousComponent::resolve(['view' => 'components.portal-shell','data' => ['title' => 'Patient Dashboard']] + (isset($attributes) && $attributes instanceof Illuminate\View\ComponentAttributeBag ? $attributes->all() : [])); ?>
<?php $component->withName('portal-shell'); ?>
<?php if ($component->shouldRender()): ?>
<?php $__env->startComponent($component->resolveView(), $component->data()); ?>
<?php if (isset($attributes) && $attributes instanceof Illuminate\View\ComponentAttributeBag): ?>
<?php $attributes = $attributes->except(\Illuminate\View\AnonymousComponent::ignoredParameterNames()); ?>
<?php endif; ?>
<?php $component->withAttributes(['title' => 'Patient Dashboard']); ?>
<div class="mb-7 flex flex-col justify-between gap-4 md:flex-row md:items-end">
 <div><span class="section-label">PATIENT PORTAL</span><h1 class="section-heading !mt-3 !text-4xl">Welcome back, <?php echo e(auth()->user()->name); ?></h1><p class="mt-3 text-slate-500">Your appointments, reports and patient-visible medical information in one secure place.</p></div>
 <a href="<?php echo e(route('appointments.create')); ?>" class="btn-primary">Book Appointment <span>↗</span></a>
</div>
<div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
 <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__currentLoopData = [['Upcoming appointment',$nextAppointment?->appointment_date?->format('d M Y') ?? 'None'],['Total appointments',$totalAppointments],['Medical reports',$reportCount],['Unread notifications',$unreadCount]]; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $s): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><div class="stat-card"><p class="text-sm font-bold text-slate-500"><?php echo e($s[0]); ?></p><p class="mt-2 text-2xl font-extrabold text-navy-900"><?php echo e($s[1]); ?></p></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
</div>
<div class="mt-6 grid gap-6 xl:grid-cols-[1.25fr_.75fr]">
 <section class="soft-panel p-6"><div class="flex items-center justify-between"><div><span class="section-label">NEXT VISIT</span><h2 class="mt-3 text-xl font-extrabold text-navy-900">Upcoming appointment</h2></div></div>
 <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($nextAppointment): ?><div class="mt-5 rounded-3xl bg-[linear-gradient(135deg,#071c40,#164f9c)] p-6 text-white"><p class="text-sm font-bold text-white/60"><?php echo e($nextAppointment->appointment_date->format('l, d M Y')); ?> · <?php echo e(substr($nextAppointment->appointment_time,0,5)); ?></p><p class="mt-2 text-2xl font-extrabold"><?php echo e($nextAppointment->doctor->name); ?></p><p class="mt-1 text-white/70"><?php echo e($nextAppointment->doctor->specialty?->name); ?></p><span class="mt-5 inline-flex rounded-full bg-white/10 px-3 py-1 text-xs font-bold"><?php echo e(ucfirst($nextAppointment->status)); ?></span></div><?php else: ?><div class="mt-5 rounded-3xl bg-slate-50 p-8 text-center"><p class="font-bold text-navy-900">No upcoming appointment</p><p class="mt-1 text-sm text-slate-500">Book your next visit when you're ready.</p></div><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
 </section>
 <section class="soft-panel p-6"><div class="flex items-center justify-between"><h2 class="text-xl font-extrabold text-navy-900">Notifications</h2><a href="<?php echo e(route('patient.notifications')); ?>" class="text-sm font-bold text-primary-700">View all</a></div><div class="mt-4 divide-y divide-slate-100"><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__empty_1 = true; $__currentLoopData = $notifications; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $n): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><div class="block py-4"><p class="font-bold text-navy-900"><?php echo e($n->title); ?></p><p class="mt-1 text-sm text-slate-500"><?php echo e($n->message); ?></p><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if(!$n->read_at): ?><form method="POST" action="<?php echo e(route('patient.notifications.read',$n)); ?>" class="mt-2"><?php echo csrf_field(); ?><button class="text-xs font-extrabold text-primary-700">View update →</button></form><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><p class="py-8 text-sm text-slate-500">You're all caught up.</p><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></div></section>
</div>
<section class="soft-panel mt-6 p-6"><div class="flex items-center justify-between"><div><span class="section-label">SECURE DOCUMENTS</span><h2 class="mt-3 text-xl font-extrabold text-navy-900">Medical Reports</h2></div><a href="<?php echo e(route('patient.reports')); ?>" class="text-sm font-bold text-primary-700">View all</a></div><div class="mt-5 grid gap-4 md:grid-cols-2"><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__empty_1 = true; $__currentLoopData = $reports; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $r): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><div class="rounded-3xl border border-slate-100 bg-slate-50 p-5"><div class="flex items-start justify-between gap-4"><div><p class="font-extrabold text-navy-900"><?php echo e($r->title); ?></p><p class="mt-1 text-sm text-slate-500"><?php echo e($r->doctor->name); ?> · <?php echo e($r->report_date->format('d M Y')); ?></p></div><span class="rounded-full bg-white px-3 py-1 text-xs font-bold text-slate-500"><?php echo e(strtoupper(pathinfo($r->file_name,PATHINFO_EXTENSION))); ?></span></div><a href="<?php echo e(route('medical-reports.download',$r)); ?>" class="mt-5 inline-flex font-extrabold text-primary-700">View / Download →</a></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><div class="rounded-3xl bg-slate-50 p-8 text-center text-sm text-slate-500 md:col-span-2">No medical reports yet.</div><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></div></section>
<section class="soft-panel mt-6 p-6"><span class="section-label">PATIENT-VISIBLE NOTES</span><h2 class="mt-3 text-xl font-extrabold text-navy-900">Recent clinical information</h2><div class="mt-5 grid gap-4 md:grid-cols-2"><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__empty_1 = true; $__currentLoopData = $medicalRecords; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $r): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><article class="rounded-3xl bg-slate-50 p-5"><p class="text-xs font-extrabold uppercase tracking-wider text-primary-600"><?php echo e(optional($r->created_at)->format('d M Y')); ?></p><p class="mt-2 text-sm leading-6 text-slate-600"><?php echo e($r->patient_visible_notes); ?></p><p class="mt-3 text-xs font-bold text-slate-400">Dr. <?php echo e($r->doctor->name); ?></p></article><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><div class="rounded-3xl bg-slate-50 p-8 text-center text-sm text-slate-500 md:col-span-2">No patient-visible clinical notes yet.</div><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></div></section>
 <?php echo $__env->renderComponent(); ?>
<?php endif; ?>
<?php if (isset($__attributesOriginalc0848eaf28452caa8d672e14d7fde2bc)): ?>
<?php $attributes = $__attributesOriginalc0848eaf28452caa8d672e14d7fde2bc; ?>
<?php unset($__attributesOriginalc0848eaf28452caa8d672e14d7fde2bc); ?>
<?php endif; ?>
<?php if (isset($__componentOriginalc0848eaf28452caa8d672e14d7fde2bc)): ?>
<?php $component = $__componentOriginalc0848eaf28452caa8d672e14d7fde2bc; ?>
<?php unset($__componentOriginalc0848eaf28452caa8d672e14d7fde2bc); ?>
<?php endif; ?>
<?php /**PATH C:\ITprojects\New folder\resources\views/dashboard/index.blade.php ENDPATH**/ ?>