<?php if (isset($component)) { $__componentOriginalc0848eaf28452caa8d672e14d7fde2bc = $component; } ?>
<?php if (isset($attributes)) { $__attributesOriginalc0848eaf28452caa8d672e14d7fde2bc = $attributes; } ?>
<?php $component = Illuminate\View\AnonymousComponent::resolve(['view' => 'components.portal-shell','data' => ['title' => 'Patient Details']] + (isset($attributes) && $attributes instanceof Illuminate\View\ComponentAttributeBag ? $attributes->all() : [])); ?>
<?php $component->withName('portal-shell'); ?>
<?php if ($component->shouldRender()): ?>
<?php $__env->startComponent($component->resolveView(), $component->data()); ?>
<?php if (isset($attributes) && $attributes instanceof Illuminate\View\ComponentAttributeBag): ?>
<?php $attributes = $attributes->except(\Illuminate\View\AnonymousComponent::ignoredParameterNames()); ?>
<?php endif; ?>
<?php $component->withAttributes(['title' => 'Patient Details']); ?>
<div class="mb-6 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><span class="section-label">PATIENT PROFILE</span><h1 class="section-heading !mt-3 !text-4xl"><?php echo e($patient->name); ?></h1><p class="mt-2 text-slate-500"><?php echo e($patient->email); ?> · <?php echo e($patient->phone ?: 'Phone not provided'); ?></p></div><div class="flex gap-2"><a href="<?php echo e(route('doctor.records.create',$patient)); ?>" class="btn-secondary">Add Medical Record</a><a href="<?php echo e(route('doctor.reports.create',$patient)); ?>" class="btn-primary">Upload Report</a></div></div>
<div class="grid gap-6 xl:grid-cols-2">
 <section class="soft-panel p-6"><div class="flex items-center justify-between"><h2 class="text-xl font-extrabold text-navy-900">Appointments</h2></div><div class="mt-4 divide-y divide-slate-100"><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__empty_1 = true; $__currentLoopData = $patient->appointments; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $a): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><div class="flex justify-between gap-4 py-4"><div><p class="font-bold"><?php echo e($a->appointment_date->format('d M Y')); ?></p><p class="text-sm text-slate-500"><?php echo e(substr($a->appointment_time,0,5)); ?></p></div><span class="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold"><?php echo e(ucfirst($a->status)); ?></span></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><p class="py-8 text-slate-500">No appointments.</p><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></div></section>
 <section class="soft-panel p-6"><h2 class="text-xl font-extrabold text-navy-900">Medical Reports</h2><div class="mt-4 divide-y divide-slate-100"><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__empty_1 = true; $__currentLoopData = $patient->reports; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $r): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><div class="flex items-center justify-between gap-4 py-4"><div><p class="font-bold"><?php echo e($r->title); ?></p><p class="text-sm text-slate-500"><?php echo e($r->report_date->format('d M Y')); ?> · <?php echo e($r->file_name); ?></p></div><a href="<?php echo e(route('medical-reports.download',$r)); ?>" class="font-bold text-primary-700">View</a></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><p class="py-8 text-slate-500">No reports yet.</p><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></div></section>
 <section class="soft-panel p-6 xl:col-span-2"><h2 class="text-xl font-extrabold text-navy-900">Clinical records</h2><div class="mt-4 grid gap-4"><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__empty_1 = true; $__currentLoopData = $patient->medicalRecords; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $r): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><article class="rounded-2xl bg-slate-50 p-5"><p class="text-xs font-extrabold uppercase tracking-wider text-primary-600"><?php echo e(optional($r->created_at)->format('d M Y')); ?></p><p class="mt-2 font-bold text-navy-900"><?php echo e($r->diagnosis ?: 'Clinical visit'); ?></p><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($r->patient_visible_notes): ?><p class="mt-2 text-sm text-slate-600"><span class="font-bold">Patient-visible:</span> <?php echo e($r->patient_visible_notes); ?></p><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?><?php if($r->doctor_notes): ?><p class="mt-2 text-sm text-slate-500"><span class="font-bold">Internal note:</span> <?php echo e($r->doctor_notes); ?></p><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></article><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><p class="py-8 text-slate-500">No clinical records yet.</p><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></div></section>
</div>
 <?php echo $__env->renderComponent(); ?>
<?php endif; ?>
<?php if (isset($__attributesOriginalc0848eaf28452caa8d672e14d7fde2bc)): ?>
<?php $attributes = $__attributesOriginalc0848eaf28452caa8d672e14d7fde2bc; ?>
<?php unset($__attributesOriginalc0848eaf28452caa8d672e14d7fde2bc); ?>
<?php endif; ?>
<?php if (isset($__componentOriginalc0848eaf28452caa8d672e14d7fde2bc)): ?>
<?php $component = $__componentOriginalc0848eaf28452caa8d672e14d7fde2bc; ?>
<?php unset($__componentOriginalc0848eaf28452caa8d672e14d7fde2bc); ?>
<?php endif; ?>
<?php /**PATH C:\ITprojects\New folder\resources\views\doctor\patients\show.blade.php ENDPATH**/ ?>