<x-portal-shell title="Patient Details">
<div class="mb-6 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><span class="section-label">PATIENT PROFILE</span><h1 class="section-heading !mt-3 !text-4xl">{{ $patient->name }}</h1><p class="mt-2 text-slate-500">{{ $patient->email }} · {{ $patient->phone ?: 'Phone not provided' }}</p></div><div class="flex gap-2"><a href="{{route('doctor.records.create',$patient)}}" class="btn-secondary">Add Medical Record</a><a href="{{route('doctor.reports.create',$patient)}}" class="btn-primary">Upload Report</a></div></div>
<div class="grid gap-6 xl:grid-cols-2">
 <section class="soft-panel p-6"><div class="flex items-center justify-between"><h2 class="text-xl font-extrabold text-navy-900">Appointments</h2></div><div class="mt-4 divide-y divide-slate-100">@forelse($patient->appointments as $a)<div class="flex flex-col justify-between gap-3 py-4 sm:flex-row sm:items-center"><div><p class="font-bold">{{ $a->appointment_date->format('d M Y') }}</p><p class="text-sm text-slate-500">{{substr($a->appointment_time,0,5)}}</p></div><div class="flex items-center gap-3"><span class="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold">{{ucfirst($a->status)}}</span>@if($a->status === 'pending')<form method="POST" action="{{route('doctor.appointments.status',$a)}}">@csrf @method('PATCH')<input type="hidden" name="status" value="confirmed"><button type="submit" class="text-xs font-extrabold text-emerald-700">Approve</button></form><form method="POST" action="{{route('doctor.appointments.status',$a)}}">@csrf @method('PATCH')<input type="hidden" name="status" value="cancelled"><button type="submit" class="text-xs font-extrabold text-rose-700">Decline</button></form>@endif</div></div>@empty<p class="py-8 text-slate-500">No appointments.</p>@endforelse</div></section>
 <section class="soft-panel p-6"><h2 class="text-xl font-extrabold text-navy-900">Medical Reports</h2><div class="mt-4 divide-y divide-slate-100">@forelse($patient->reports as $r)<div class="flex items-center justify-between gap-4 py-4"><div><p class="font-bold">{{ $r->title }}</p><p class="text-sm text-slate-500">{{ $r->report_date->format('d M Y') }} · {{ $r->file_name }}</p></div><a href="{{route('medical-reports.download',$r)}}" class="font-bold text-primary-700">View</a></div>@empty<p class="py-8 text-slate-500">No reports yet.</p>@endforelse</div></section>
 <section class="soft-panel p-6 xl:col-span-2"><h2 class="text-xl font-extrabold text-navy-900">Send patient notification</h2><p class="mt-1 text-sm text-slate-500">Send a message that the patient can see in their portal notifications.</p><form method="POST" action="{{ route('doctor.patient.notifications.send', $patient) }}" class="mt-4 grid gap-3">@csrf<input name="title" value="{{ old('title') }}" maxlength="120" class="input-field" placeholder="Notification title" required><textarea name="message" maxlength="1000" rows="3" class="input-field" placeholder="Write your message for the patient" required>{{ old('message') }}</textarea>@error('title')<p class="text-sm font-semibold text-rose-600">{{ $message }}</p>@enderror @error('message')<p class="text-sm font-semibold text-rose-600">{{ $message }}</p>@enderror<div><button class="btn-primary" type="submit">Send Notification</button></div></form></section>
 <section class="soft-panel p-6 xl:col-span-2"><h2 class="text-xl font-extrabold text-navy-900">Clinical records</h2><div class="mt-4 grid gap-4">@forelse($patient->medicalRecords as $r)<article class="rounded-2xl bg-slate-50 p-5"><p class="text-xs font-extrabold uppercase tracking-wider text-primary-600">{{optional($r->created_at)->format('d M Y')}}</p><p class="mt-2 font-bold text-navy-900">{{ $r->diagnosis ?: 'Clinical visit' }}</p>@if($r->patient_visible_notes)<p class="mt-2 text-sm text-slate-600"><span class="font-bold">Patient-visible:</span> {{ $r->patient_visible_notes }}</p>@endif@if($r->doctor_notes)<p class="mt-2 text-sm text-slate-500"><span class="font-bold">Internal note:</span> {{ $r->doctor_notes }}</p>@endif</article>@empty<p class="py-8 text-slate-500">No clinical records yet.</p>@endforelse</div></section>
</div>
</x-portal-shell>
